# Generated by Django 2.2.6 on 2019-10-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('last_price', models.FloatField()),
                ('Total', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
