# Generated by Django 2.2.6 on 2019-10-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading', '0003_user_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytransaction',
            name='avg_price',
            field=models.FloatField(default=0),
        ),
    ]
