# Generated by Django 2.2.6 on 2019-10-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading', '0006_auto_20191019_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytransaction',
            name='date',
        ),
    ]
